name: Auto Add to Project

on:
  issues:
    types: [opened]

jobs:
  add-to-project:
    name: Add issue to project
    runs-with: ubuntu-latest
    steps:
      - name: Add Issue to Project
        uses: actions/add-to-project@v1
        with:
          # Your Project URL number from Step 1
          project-url: https://github.com{{ github.repository_owner }}/projects/4
          # The secret token you saved in Step 3
          github-token: ${{ secrets.PERSONAL_PROJECT_TOKEN }}
